version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-fohow
    restart: always
    environment:
      - MYSQL_DATABASE=fohow-prod
      - MYSQL_ROOT_PASSWORD=pass_prod
    volumes:
      - mysql_fohow_data:/var/lib/mysql/

  startbot:
    image: fohow-api:latest
    command: sh -c "poetry run python manage.py startbot"
    restart: always
    depends_on:    
      - api
    volumes:
      - .:/fohow
    env_file:
      - docker-compose.env
    environment:
      - DOCKER_CONTAINER=True
    container_name: solevar_startbot

  redis: 
    image: redis:latest
    container_name: redis-fohow
    restart: always
    ports:
      - "6379:6379"

  fohow-api:
    build: .
    image: fohow-api
    command:
      - sh
      - -c
      - |
        poetry run python manage.py collectstatic --noinput &&
        poetry run python manage.py migrate &&
        poetry run gunicorn Fohow.wsgi:application -b :8000
    env_file:
      - docker-compose.env
    environment:
      - DOCKER_CONTAINER=True
      - VIRTUAL_HOST=fohowomsk.space
      - LETSENCRYPT_HOST=fohowomsk.space
    ports:
      - "8000:8000" 
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/fohow
      - static_volume:/fohow/static
      - media_volume:/fohow/media
    container_name: fohow-api
  nginx:
    build: 
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_fohow
    image: nginx_fohow
    volumes:
      - static_volume:/fohow/static
      - media_volume:/fohow/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - fohow-api
    ports:
      - "80:80"
      - "443:443"
  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: fohow_acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh


volumes:
  mysql_fohow_data: null
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme: