# Generated by Django 4.2 on 2023-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='context',
            new_name='text',
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
