# Generated by Django 4.2 on 2023-12-25 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_context_reviews_text_reviews_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='method_of_application',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging_standard',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
